name: REEdesign
favicon: null
layout_spectrum: 0.00101
typography_spectrum: 0.64047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edece8'
    - '#ef737d'
    - '#173253'
    - '#0077a1'
    - '#c7b74a'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
