name: REEdesign
favicon: null
layout_spectrum: 0.00101
typography_spectrum: 0.50334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2baba'
    - '#302f35'
    - '#030305'
    - '#6f0b32'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
