name: REEdesign
favicon: null
layout_spectrum: 0.267285
typography_spectrum: 0.50334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#919188'
    - '#3A2F28'
    - '#B4ACA3'
    - '#FEFFFF'
    - '#0D0B0D'
  brandStrength: 0.9123103
  lightness: 0.9003792
  saturation: 0.6947724
  rhythmicContrast: 0.6635751
purpose: []
