name: redesign
favicon: null
layout_spectrum: 0.75656
typography_spectrum: 0.10925
title: robelgardesign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#656565'
    - '#404040'
    - '#131313'
    - '#949494'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
