name: REEdesign
favicon: null
layout_spectrum: 0.5101
typography_spectrum: 0.50334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b89867'
    - '#f4cb00'
    - '#060407'
    - '#62684c'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
