name: REEdesign
favicon: null
layout_spectrum: 0.99277
typography_spectrum: 0.42459
title: Rob Elgar Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141205'
    - '#5f3004'
    - '#fefdf9'
    - '#7d6e57'
    - '#dccdae'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
